### Create user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "asd1@asd.com",
    "password": "asdf"
}

### Signin user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "asd1@asd.com",
    "password": "asdf"
}

### Signout user
POST http://localhost:3000/auth/signout

### 
GET http://localhost:3000/auth/whoami
