### Make a guess
POST http://localhost:3000/guess/
content-type: application/json

{
    "word": "naked"
}

### Create custom game
POST http://localhost:3000/createCustomGame
content-type: application/json

{
    "length": 10,
    "guesses": 10,
    "lang": "eng"
}


### Get state
GET http://localhost:3000/state

